//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: wrapperapec Created :
// Initializer: wrapperapec.cxx

#include <XSUser/UserInterface/xstcl.h>
#include <dlfcn.h>
#include  "wrapperapecFunctionMap.h"
#include  <XSFunctions/Utilities/XSCall.h>
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Wrapperapec_Init(Tcl_Interp* tclInterp);
extern "C" int Wrapperapec_SafeInit(Tcl_Interp* tclInterp);

int Wrapperapec_Init(Tcl_Interp* tclInterp)
{
  dlopen("libpython3.9.so", RTLD_LAZY | RTLD_GLOBAL);
        return Wrapperapec_SafeInit(tclInterp);
}

int Wrapperapec_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "wrapperapec";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        XSModelFunction::updateComponentList
              ("/scratch1/avalderr/pyspectrum/model.dat");
        createwrapperapecFunctionMap();
        return TCL_OK;

}

